#!/usr/bin/perl


use constant EXIT         => 0x00;
use constant IADD         => 0x01;
use constant ISUB         => 0x02;
use constant IMUL         => 0x03;
use constant IDIV         => 0x04;
use constant STORE_STRING => 0x05;
use constant STORE_INT    => 0x06;
use constant PRINT_STRING => 0x07;
use constant PRINT_INT    => 0x08;
use constant SYSTEM_STR   => 0x09;

use constant EMIT_LABEL => 0x0a;
use constant JUMP_LABEL => 0x0b;


sub store_int
{
    my ( $reg, $val ) = (@_);

    print chr STORE_INT;
    print chr $reg;
    print chr $val;
}

sub print_int
{
    my ($reg) = (@_);
    print chr PRINT_INT;
    print chr $reg;
}
sub emit_label
{
    my ($l) = (@_);
    print chr EMIT_LABEL;
    print ord $l;
}

sub jump_label
{
    my ($l) = (@_);
    print chr JUMP_LABEL;
    print ord $l;
}




store_int( 0x00, 0 );
store_int( 0x01, 1 );

emit_label( "A" );

print chr IADD;
print chr 0x00;
print chr 0x00;
print chr 0x01;

print_int( 0x00 );

jump_label( "A" );

