#!/usr/bin/perl
#
# A simple script which will allow some values to be used.
#
#  1.  Prints regs.
#  2.  Do some addition.
#  3.  print registers.

use constant EXIT         => 0x00;
use constant IADD         => 0x01;
use constant ISUB         => 0x02;
use constant IMUL         => 0x03;
use constant IDIV         => 0x04;
use constant STORE_STRING => 0x05;
use constant STORE_INT    => 0x06;
use constant PRINT_STRING => 0x07;
use constant PRINT_INT    => 0x08;
use constant SYSTEM_STR   => 0x09;

use constant EMIT_LABEL => 0x0a;
use constant JUMP_LABEL => 0x0b;


sub store_string
{
    my ( $reg, $str ) = (@_);

    print chr STORE_STRING;
    print chr $reg;

    my $len = length($str);
    print chr $len;
    print $str;
}


sub print_string
{
    my ($reg) = (@_);
    print chr PRINT_STRING;
    print chr $reg;
}

sub store_int
{
    my ( $reg, $val ) = (@_);

    print chr STORE_INT;
    print chr $reg;
    print chr $val;
}

sub print_int
{
    my ($reg) = (@_);
    print chr PRINT_INT;
    print chr $reg;
}

sub system_string
{
    my ($reg) = (@_);
    print chr SYSTEM_STR;
    print chr $reg;
}


sub add_print
{
    my( $a, $b ) = ( @_ );

    print chr STORE_INT;
    print chr 1;
    print chr $a;

    print chr STORE_INT;
    print chr 2;
    print chr $b;

    print chr IADD;
    print chr 3;
    print chr 1;
    print chr 2;

    print chr PRINT_INT;
    print chr 3;

}


#
#  Store a string in a register - then print it out.
#
store_string( 0x02, "Kemp" );
print_string(0x02);


#
#  Store an integer in a register, then print it out.
#
store_int( 0x00, 32 );
print_int(0x00);

#
#  Store a string in a register, then execute it.
#
store_string( 0x01, "/bin/ls" );
system_string(0x01);


#
#  This is nasty but just to test.
#
#  Add two numbers, via registers, then output the result.
add_print( 3, 8 );

store_int( 0x01, 0xff );
print_int( 0x01 );

exit;


